# railway.toml (put at repo root)
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/ready"
restartPolicyType = "ON_FAILURE"

